### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#17]
### Description

Alterações a serem feitas: 
- Descrever melhor como de fato aconteceu o trabalho da equipe toda; 
- Melhorar descrição da metodologia nessa página também; 
- Adicionar outros versionamentos; 
- Adicionar REFERÊNCIAS ou outras fontes consultadas (se possível, com links); 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PabloGJBS** [comment]
Ta na mão ༼ つ ◕_◕ ༽つ
