### ISSUE TITLE
Prototipação 

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#18]
### Description. What happened?

Alterações a serem feitas: 
- Melhorar descrição da prototipação -> pois o nível do protótipo está alto, porém, a descrição do texto não; 
- Adicionar tópico de metodologia (citar coleta de pontos de vista e consensos entre a equipe);
- Revelar no texto sobre como aconteceu o trabalho em equipe -> acredito que no próprio tópico de metodologia; 
- Adicionar referências ou possíveis consultas realizadas (linkar); 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luanatorress** [comment]
Adicionada descrição da prototipação do protótipo de alta fidelidade, Metologia, Fluxo e Escolha de Telas. 
Adicionadas referencias e novo versionamento.
Issue Concluída.
