### ISSUE TITLE
Entrevista 

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#19]
### Description. What happened?

O que deve ser alterado: 
- Descrever mais sobre o trabalho em equipe realizado na parte de metodologia; 
- Se achar necessário descrever mais sobre cada um dos 6 tópicos do DECIDE; 
- Melhorar descrição dos resultados obtidos (explicar mais pois está muito conciso) -> tentar trazer informações comprobatórias; 
- Colocar outra pessoa no versionamento.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PabloGJBS** [comment]
Corrijido (☞ﾟヮﾟ)☞
