### ISSUE TITLE
5W2H

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#20]
### Description. What happened?

O que deve ser alterado: 
- Adicionar tópico de metodologia; 
- Detalhar/descrever como foi realizado o trabalho em equipe, diferentes pontos de vistas apresentados da equipe (mesmo que não utilizados); 
- Inserir fontes que embasaram as colocações ou links para artefatos correlacionados; 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Cleberbrant** [comment]
Foi melhorado o tópico de metodologia, explicando melhor como o trabalho em equipe foi feito para definiçao inicial das funcionalidades, e como o trabalho que eu e o Matheus Silverio foi feito para definirmos melhor os documentos, além disso, foi complementado tambem nas fontes que faltavam.
