### ISSUE TITLE
MOSCOW 

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#22]
### Description. What happened?

O que deve ser alterado: 
- Descrever sobre as técnicas de elicitação utilizadas; 
- Adicionar fontes consultadas (se não lembrar quais foram, adicionar novas); 
- Adicionar tópico de metodologia -> descrever como foi realizado o trabalho em equipe e diferentes pontos de vistas apresentados da equipe (mesmo os que não foram considerados relevantes); 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jpanacleto2** [comment]
Foram realizadas as correções sugeridas nos artefatos solicitados, podendo serem visualizadas em [MOSCOW](https://unbarqdsw2024-1.github.io/2024.1_G8_UnBreja/#/Base/1.4.4.moscow)
