### ISSUE TITLE
Léxicos 

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#23]
### Description. What happened?

O que deve ser alterado: 
- Utilizar mais os termos nos impactos; 
- Há noção que não parece noção como é o caso do L05 Mensagem, onde o próprio termo é usado em sua definição; 
- Adicionar referências ou fontes consultadas (linkar corretamente); 
- Adicionar tópico de Metodologia, e, incluir além da metodologia o que foi discutido entre a equipe (diferentes pontos de vista);

### Code of Conduct

- [X] #38

**Comment by Augcamp** [comment]
- [x] Utilizar mais os termos nos impactos;

- [x] Há noção que não parece noção como é o caso do L05 Mensagem, onde o próprio termo é usado em sua definição;

- [x] Adicionar referências ou fontes consultadas (linkar corretamente);

- [x] Adicionar tópico de Metodologia, e, incluir além da metodologia o que foi discutido entre a equipe (diferentes pontos de vista);
