### ISSUE TITLE
Glossário 

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#24]
### Description. What happened?

O que deve ser alterado: 
- Adicionar metodologia (e incluir uma parte para descrever sobre os pontos de vista diferentes da equipe)
- Adicionar referências ou fontes consultadas; 
- A professora cita que o foco é feito apenas na descrição, descobrir se existiria algum outro foco que poderia ser utilizado também -> Se encontrar, então, adicionar esse outro foco;  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Augcamp** [comment]
O que deve ser alterado:

- [x] Adicionar metodologia (e incluir uma parte para descrever sobre os pontos de vista diferentes da equipe)

- [x] Adicionar referências ou fontes consultadas

- [ ] A professora cita que o foco é feito apenas na descrição, descobrir se existiria algum outro foco que poderia ser utilizado também -> Se encontrar, então, adicionar esse outro foco;
