### ISSUE TITLE
Unpack - Entendimento (Design Sprint)

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#25]
### Description. What happened?

O que deve ser alterado: 
- É necessário criar uma aba para essa etapa (pois, até o momento está sendo feito apenas na aba de Brainstorming); 
- Os links estão quebrando quando são clicáveis (arrumar linkagem corretamente); 
- Adicionar tópico de metodologia, e descrever DECIDE e Test; 
- Adicionar mais alguma referência; 
- No tópico de metodologia também detalhar/descrever como foi realizado o trabalho em equipe e diferentes pontos de vistas apresentados da equipe (mesmo que não considerados na elaboração do artefato); 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by edilbertocantuaria** [comment]
O que deve ser alterado:

- [x] 1. É necessário criar uma aba para essa etapa (pois, até o momento está sendo feito apenas na aba de Brainstorming);
- [x] 2. Os links estão quebrando quando são clicáveis (arrumar linkagem corretamente);
- [x] 3. Adicionar tópico de metodologia, e descrever DECIDE e Test;
- [x] 4. Adicionar mais alguma referência;
- [x] 5. No tópico de metodologia também detalhar/descrever como foi realizado o trabalho em equipe e diferentes pontos de vistas apresentados da equipe (mesmo que não considerados na elaboração do artefato);
