### ISSUE TITLE
DECIDE - Escolha (Design Sprint) 

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#27]
### Description. What happened?

O que deve ser feito: 
- Adicionar essa aba e as respectivas informações pertinentes; 
- Não esquecer de adicionar os diferentes pontos de vistas da equipe discutidos em reunião; 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Weslin-0101** [comment]
Task feita. Esperando a revisão
