### ISSUE TITLE
Test - Verificação e Validação (Design Sprint)

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#29]
### Description. What happened?

O que deve ser feito: 
- Deve-se criar a aba para essa parte, descrevendo conforme o modelo apresentado; 
- Citar novamente nessa aba também a entrevista realizada para a validação do protótipo, além do que será adicionado a mais nesse artefato; 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luanatorress** [comment]
Página de validação criada com resultados e impressões dadas na entrevista. 
Issue concluída com sucesso.
