### ISSUE TITLE
fix: diagrama de pacotes 

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#42]
### Quais modificações devem ser realizadas no documento? 

- [x] alterar menções no texto de 'chat' por 'bate-papo'; 
- [x] alterar menções no texto de 'match' por 'combinar';
- [x] alterar menções no texto de 'bucket' por algum outro termo em português que seja condizente; 
- [x] colocar todos os pacotes iniciados com a letra maiúscula; 
- [x] melhorar semântica -> a semântica ainda é apresentada de forma superficial na visão da professora; 
- [x] melhorar texto no que tange o senso crítico e discussão do trabalho em equipe -> deve-se adicionar o tópico "Conclusão" ao final do texto para explicar os diferentes pontos de vistas utilizados na elaboração do artefato;

**Comment by suzaneduarte** [comment]
NÃO ESQUECER: 
- colocar na tabela de versionamento exatamente o que cada um arrumou a partir do que foi solicitado; 
- fechar essa issue assim que commitar as alterações; 
-  quando commitar a alteração citar o número da issue no commit. exemplo: 
`#42 fix: alterando semântica do diagrama de pacotes`

**Comment by jpanacleto2** [comment]
Foram realizadas todas as alterações solicitadas no documento de diagrama de pacotes.
