### ISSUE TITLE
fix: diagrama de estados 

### ISSUE THREAD

**Issue by suzaneduarte** [UnBArqDsw2024-1/2024.1_G8_UnBreja#46]
### Quais modificações devem ser realizadas no documento? 

- [ ] alterar menções de termos em inglês para português, por exemplo, alterar 'chat' por 'bate-papo' ou 'match' por 'combinar' e demais alterações pertinentes; 
- [ ] melhorar texto no que tange o senso crítico e discussão do trabalho em equipe -> deve-se adicionar o tópico "Conclusão" ao final do texto para explicar os diferentes pontos de vistas utilizados na elaboração do artefato; 
- [ ] no que tange os pseudoestados de início e fim, adicionar um fim para o fluxo geral -> repare que o fim está no subfluxo do 'chat'; 
- [ ] elaborar mais a metodologia, pois para a professora ainda está simples;

**Comment by luanatorress** [comment]
Todas as alterações foram realizadas com sucesso seguindo o padrão de commit #__ fix.
